apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-mysql
spec:
  template:
    spec:
      containers:
      - name: katib-mysql
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 1024Mi
