apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        resources:
          requests:
            cpu: 1600m
            memory: 4096Mi
          limits:
            cpu: 3200m
            memory: 8192Mi
