apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - NetworkPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration
resources:
- ../common/cert-manager/base
- ../common/cert-manager/kubeflow-issuer/base
- ../common/istio/istio-crds/base
- ../common/istio/istio-namespace/base
- ../common/istio/istio-install/overlays/oauth2-proxy
- ../common/oauth2-proxy/overlays/m2m-dex-only
- ../common/dex/overlays/oauth2-proxy
- ../common/knative/knative-serving/overlays/gateways
- ../common/istio/cluster-local-gateway/base
- ../common/kubeflow-namespace/base
- ../common/networkpolicies/base
- ../common/kubeflow-roles/base
- ../common/istio/kubeflow-istio-resources/base
- ../applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
- ../applications/katib/upstream/installs/katib-with-kubeflow
- ../applications/centraldashboard/overlays/oauth2-proxy
- ../applications/admission-webhook/upstream/overlays/cert-manager
- ../applications/jupyter/jupyter-web-app/upstream/overlays/istio
- ../applications/jupyter/notebook-controller/upstream/overlays/kubeflow
- ../applications/profiles/pss
- ../applications/pvcviewer-controller/upstream/base
- ../applications/volumes-web-app/upstream/overlays/istio
- ../applications/training-operator/upstream/overlays/kubeflow
- ../common/user-namespace/base
- ../applications/kserve/kserve
- ../applications/kserve/models-web-app/overlays/kubeflow
patchesStrategicMerge:
- mini-kubeflow/patches/pipeline/ml-pipeline-ui.yaml
- mini-kubeflow/patches/pipeline/kubeflow-pipelines-profile-controller.yaml
- mini-kubeflow/patches/pipeline/ml-pipeline-scheduledworkflow.yaml
- mini-kubeflow/patches/pipeline/ml-pipeline.yaml
- mini-kubeflow/patches/pipeline/ml-pipeline-visualizationserver.yaml
- mini-kubeflow/patches/pipeline/ml-pipeline-viewer-crd.yaml
- mini-kubeflow/patches/pipeline/ml-pipeline-persistenceagent.yaml
- mini-kubeflow/patches/core/model-registry-ui.yaml
- mini-kubeflow/patches/core/katib-ui.yaml
- mini-kubeflow/patches/core/cluster-jwks-proxy.yaml
- mini-kubeflow/patches/core/deployment.yaml
- mini-kubeflow/patches/core/centraldashboard.yaml
- mini-kubeflow/patches/core/metadata-postgres-db.yaml
- mini-kubeflow/patches/core/controller-manager.yaml
- mini-kubeflow/patches/core/net-istio-controller.yaml
- mini-kubeflow/patches/core/kserve-models-web-app.yaml
- mini-kubeflow/patches/core/katib-controller.yaml
- mini-kubeflow/patches/core/cert-manager-cainjector.yaml
- mini-kubeflow/patches/core/katib-postgres.yaml
- mini-kubeflow/patches/core/metadata-writer.yaml
- mini-kubeflow/patches/core/httpbin.yaml
- mini-kubeflow/patches/core/oauth2-proxy.yaml
- mini-kubeflow/patches/core/istiod.yaml
- mini-kubeflow/patches/core/activator.yaml
- mini-kubeflow/patches/core/prometheus.yaml
- mini-kubeflow/patches/core/cache-deployer-deployment.yaml
- mini-kubeflow/patches/core/cache-server.yaml
- mini-kubeflow/patches/core/spark-operator-controller.yaml
- mini-kubeflow/patches/core/mysql.yaml
- mini-kubeflow/patches/core/cluster-local-gateway.yaml
- mini-kubeflow/patches/core/workflow-controller.yaml
- mini-kubeflow/patches/core/argo-server.yaml
- mini-kubeflow/patches/core/kserve-controller-manager.yaml
- mini-kubeflow/patches/core/grafana.yaml
- mini-kubeflow/patches/core/dex.yaml
- mini-kubeflow/patches/core/postgres.yaml
- mini-kubeflow/patches/core/*.yaml
- mini-kubeflow/patches/core/mt-broker-filter.yaml
- mini-kubeflow/patches/core/eventing-controller.yaml
- mini-kubeflow/patches/core/model-registry-db.yaml
- mini-kubeflow/patches/core/metadata-envoy-deployment.yaml
- mini-kubeflow/patches/core/placeholder.yaml
- mini-kubeflow/patches/core/katib-db-manager.yaml
- mini-kubeflow/patches/core/metadata-grpc-deployment.yaml
- mini-kubeflow/patches/core/istio-ingressgateway.yaml
- mini-kubeflow/patches/core/imc-controller.yaml
- mini-kubeflow/patches/core/minio.yaml
- mini-kubeflow/patches/core/cloudsqlproxy.yaml
- mini-kubeflow/patches/core/model-registry-deployment.yaml
- mini-kubeflow/patches/core/metadata-db.yaml
- mini-kubeflow/patches/core/proxy-agent.yaml
- mini-kubeflow/patches/core/katib-mysql.yaml
- mini-kubeflow/patches/training-operator/training-operator.yaml
- mini-kubeflow/patches/training-operator/training-operator-v2.yaml
