apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
spec:
  template:
    spec:
      containers:
      - name: katib-db-manager
        resources:
          requests:
            cpu: 200m
            memory: 409Mi
          limits:
            cpu: 400m
            memory: 819Mi
