apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
spec:
  template:
    spec:
      containers:
      - name: placeholder
        resources:
          requests:
            cpu: 200m
            memory: 409Mi
          limits:
            cpu: 400m
            memory: 819Mi
